import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import ImageSlider from "@/components/ImageSlider";
import slide1 from "../public/assets/projects/cyclistic_slides/slide-1.png";
import slide2 from "../public/assets/projects/cyclistic_slides/slide-2.png";
import slide3 from "../public/assets/projects/cyclistic_slides/slide-3.png";
import slide4 from "../public/assets/projects/cyclistic_slides/slide-4.png";
import slide5 from "../public/assets/projects/cyclistic_slides/slide-5.png";
import slide6 from "../public/assets/projects/cyclistic_slides/slide-6.png";
import slide7 from "../public/assets/projects/cyclistic_slides/slide-7.png";
import slide8 from "../public/assets/projects/cyclistic_slides/slide-8.png";
import slide9 from "../public/assets/projects/cyclistic_slides/slide-9.png";
import slide10 from "../public/assets/projects/cyclistic_slides/slide-10.png";
import slide11 from "../public/assets/projects/cyclistic_slides/slide-11.png";
import slide12 from "../public/assets/projects/cyclistic_slides/slide-12.png";
import slide13 from "../public/assets/projects/cyclistic_slides/slide-13.png";
import caseStudyCyc from "../public/assets/projects/case-study-cyc1.png";
import { RiRadioButtonFill } from "react-icons/ri";

const slideImages = [
  slide1,
  slide2,
  slide3,
  slide4,
  slide5,
  slide6,
  slide7,
  slide8,
  slide9,
  slide10,
  slide11,
  slide12,
  slide13,
];

const CaseStudyCyclistic = () => {
  return (
    <div>
      <Head>
        <title>Case Study - Cyclistic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <div className="relative w-screen h-[50vh]">
          <div className="absolute w-full h-[50vh] top-0 left-0 bg-black/70 z-10" />
          <Image
            className="absolute z-1"
            style={{ objectFit: "cover" }}
            src={caseStudyCyc}
            fill
            alt="mern image"
          />
          <div className="absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] text-white z-10 p-2">
            <h2 className="py-2">Case Study - Cyclistic</h2>
          </div>
        </div>

        <div className="grid md:grid-cols-5 gap-8 py-8 max-w-[1240px] mx-auto p-2">
          <div className="col-span-4">
            <h2 className="mb-5">Description</h2>
            <p>
              Google Data Analytics capstone project in which, a bike share
              company named Cyclistic, manages a fleet of 5,824 geotracked
              bicycles across 692 Chicago stations. To enhance growth, they
              focus on converting casual riders to annual members using data
              insights and targeted marketing tactics. The data underwent
              rigorous cleaning and analysis, employing Excel and R, and the
              results were illustrated through insightful visualizations and a
              concise PowerPoint presentation.
            </p>
            <a
              href="https://divvy-tripdata.s3.amazonaws.com/index.html"
              target="_blank"
              rel="noreferrer"
            >
              <button className="mt-4 mr-8 px-8 py-2">Data Source</button>
            </a>
          </div>

          <div className="py-4 rounded-xl col-span-4 md:col-span-1 shadow-xl shadow-gray-400">
            <div className="p-2">
              <p className="pb-2 text-center font-bold">Skills Demonstrated</p>
              <div className="grid grid-cols-3 md:grid-cols-1">
                <p className="flex items-center py-2">
                  <RiRadioButtonFill className="pr-1" /> Excel
                </p>
                <p className="flex items-center py-2">
                  <RiRadioButtonFill className="pr-1" /> R
                </p>
                <p className="flex items-center py-2">
                  <RiRadioButtonFill className="pr-1" /> RStudio
                </p>
              </div>
            </div>
          </div>
          <Link href="/#projects">
            <p className="cursor-pointer underline">Go Back</p>
          </Link>
        </div>
        <div className="flex flex-col items-center justify-center">
          <ImageSlider slideImages={slideImages} />
        </div>
      </div>
      <br />
    </div>
  );
};

export default CaseStudyCyclistic;
