import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import ViewImage from "@/components/ViewImage";
import repeatCalls from "../public/assets/projects/business_intelligence/bg_repeat_calls.png";
import { RiRadioButtonFill } from "react-icons/ri";

const CustomerServiceDashboard = () => {
  return (
    <div>
      <Head>
        <title>Customer Service Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <div className="relative w-screen h-[50vh]">
          <div className="absolute w-full h-[50vh] top-0 left-0 bg-black/70 z-10" />
          <Image
            className="absolute z-1"
            style={{ objectFit: "cover" }}
            src={repeatCalls}
            fill
            alt="repeat calls image"
          />
          <div className="absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] text-white z-10 p-2">
            <h2 className="py-2">Customer Service Dashboard</h2>
          </div>
        </div>

        <div className="grid md:grid-cols-5 gap-8 py-8 max-w-[1240px] mx-auto p-2">
          <div className="col-span-4">
            <h2 className="mb-5">Description</h2>
            <p>
              Google Business Intelligence capstone project in which, I was
              tasked with creating a comprehensive dashboard to address the
              needs of Google Fiber's customer service team. The primary goal of
              this project was to determine the frequency of customer calls to
              customer support after their initial inquiry, providing insights
              into the effectiveness of the team in addressing customer
              questions on the first interaction. The dashboard also aimed to
              shed light on the types of issues that led to repeat calls and to
              explore repeat caller trends in three different market cities.
              Additionally, the dashboard was designed to offer stakeholders the
              ability to view trends by week, month, and quarter.
            </p>
            <a
              href="https://public.tableau.com/app/profile/jr.fitz/viz/CustomerServiceInsights/OverviewofRepeatCalls"
              target="_blank"
              rel="noreferrer"
            >
              <button className="mt-4 mr-8 px-8 py-2">Dashboard</button>
            </a>
            <ViewImage />
          </div>

          <div className="py-4 rounded-xl col-span-4 md:col-span-1 shadow-xl shadow-gray-400">
            <div className="p-2">
              <p className="pb-2 text-center font-bold">Skills Demonstrated</p>
              <div className="grid grid-cols-3 md:grid-cols-1">
                <p className="flex items-center py-2">
                  <RiRadioButtonFill className="pr-1" /> Data Integration
                </p>
                <p className="flex items-center py-2">
                  <RiRadioButtonFill className="pr-1" /> Data Visualization
                </p>
                <p className="flex items-center py-2">
                  <RiRadioButtonFill className="pr-1" /> Data Analysis
                </p>
                <p className="flex items-center py-2">
                  <RiRadioButtonFill className="pr-1" /> Dashboard Design
                </p>
                <p className="flex items-center py-2">
                  <RiRadioButtonFill className="pr-1" /> Time Series Analysis
                </p>
                <p className="flex items-center py-2">
                  <RiRadioButtonFill className="pr-1" /> Report Documentation
                </p>
              </div>
            </div>
          </div>
          <Link href="/#projects">
            <p className="cursor-pointer underline">Go Back</p>
          </Link>
          {/* <ViewImage /> */}
        </div>
      </div>
    </div>
  );
};

export default CustomerServiceDashboard;
