import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import goGameImage from "../public/assets/projects/go-game.png";
import { RiRadioButtonFill } from "react-icons/ri";

const Gogame = () => {
  return (
    <div>
      <Head>
        <title>Go Guessing Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <div className="relative w-screen h-[50vh]">
          <div className="absolute w-full h-[50vh] top-0 left-0 bg-black/70 z-10" />
          <Image
            className="absolute z-1"
            style={{ objectFit: "cover" }}
            src={goGameImage}
            fill
            alt="go game image"
          />
          <div className="absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] text-white z-10 p-2">
            <h2 className="py-2">Go Guessing Game</h2>
          </div>
        </div>

        <div className="grid md:grid-cols-5 gap-8 py-8 max-w-[1240px] mx-auto p-2">
          <div className="col-span-4">
            <h2 className="mb-5">Description</h2>
            <p>
              This is a number guessing game written in Go. It generates a
              random number between 1 and 100 and allows the user to guess the
              number. The user has a limited number of guesses to select the
              correct number. If the user fails to guess the correct number
              within the allowed number of guesses, the game is over and the
              correct number is displayed. If the user guesses the correct
              number, a congratulatory message is displayed. This project
              demonstrates the use of random number generation, user input and
              conditional statements in Go.
            </p>
            <a
              href="https://github.com/devjojr/go-guessing-game"
              target="_blank"
              rel="noreferrer"
            >
              <button className="mt-4 mr-8 px-8 py-2">Code</button>
            </a>
          </div>

          <div className="py-4 rounded-xl col-span-4 md:col-span-1 shadow-xl shadow-gray-400">
            <div className="p-2">
              <p className="pb-2 text-center font-bold">Skills Demonstrated</p>
              <div className="grid grid-cols-3 md:grid-cols-1">
                <p className="flex items-center py-2">
                  <RiRadioButtonFill className="pr-1" /> Go
                </p>
              </div>
            </div>
          </div>
          <Link href="/#projects">
            <p className="cursor-pointer underline">Go Back</p>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Gogame;
