import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import mernTodoImage from "../public/assets/projects/mern-todo.png";
import { RiRadioButtonFill } from "react-icons/ri";

const Merntodo = () => {
  return (
    <div>
      <Head>
        <title>MERN Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <div className="relative w-screen h-[50vh]">
          <div className="absolute w-full h-[50vh] top-0 left-0 bg-black/70 z-10" />
          <Image
            className="absolute z-1"
            style={{ objectFit: "cover" }}
            src={mernTodoImage}
            fill
            alt="mern image"
          />
          <div className="absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] text-white z-10 p-2">
            <h2 className="py-2">MERN TODO</h2>
          </div>
        </div>

        <div className="grid md:grid-cols-5 gap-8 py-8 max-w-[1240px] mx-auto p-2">
          <div className="col-span-4">
            <h2 className="mb-5">Description</h2>
            <p>
              This is a full-stack todo application built using the MERN
              (MongoDB, Express, React, Node.js) stack, with JWT (JSON Web
              Token) for authentication. The app allows users to create, read,
              and delete todo items, as well as sign up and log in securely
              using JWT. JWT is used to authenticate users and protect routes on
              the server-side. The front-end is built using React and Bulma. The
              back-end is built using Node.js, Express, and MongoDB, and uses
              Mongoose for database interaction. This project allowed me to
              deepen my understanding of the MERN stack, RESTful API design,
              user authentication, and CRUD operations.
            </p>
            <a
              href="https://github.com/devjojr/mern-todo"
              target="_blank"
              rel="noreferrer"
            >
              <button className="mt-4 mr-8 px-8 py-2">Code</button>
            </a>
          </div>

          <div className="py-4 rounded-xl col-span-4 md:col-span-1 shadow-xl shadow-gray-400">
            <div className="p-2">
              <p className="pb-2 text-center font-bold">Skills Demonstrated</p>
              <div className="grid grid-cols-3 md:grid-cols-1">
                <p className="flex items-center py-2">
                  <RiRadioButtonFill className="pr-1" /> MongoDB
                </p>
                <p className="flex items-center py-2">
                  <RiRadioButtonFill className="pr-1" /> Express
                </p>
                <p className="flex items-center py-2 text-[#141b24]">
                  <RiRadioButtonFill className="pr-1" /> React
                </p>
                <p className="flex items-center py-2 text-[#141b24]">
                  <RiRadioButtonFill className="pr-1" /> Node.js
                </p>
                <p className="flex items-center py-2 text-[#141b24]">
                  <RiRadioButtonFill className="pr-1" /> JSON Web Token
                </p>
                <p className="flex items-center py-2 text-[#141b24]">
                  <RiRadioButtonFill className="pr-1" /> Bulma
                </p>
              </div>
            </div>
          </div>
          <Link href="/#projects">
            <p className="cursor-pointer underline">Go Back</p>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Merntodo;
