import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import pythonGenImage from "../public/assets/projects/py-page-gen.png";
import { RiRadioButtonFill } from "react-icons/ri";

const Merntodo = () => {
  return (
    <div>
      <Head>
        <title>Python Webpage Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <div className="relative w-screen h-[50vh]">
          <div className="absolute w-full h-[50vh] top-0 left-0 bg-black/70 z-10" />
          <Image
            className="absolute z-1"
            style={{ objectFit: "cover" }}
            src={pythonGenImage}
            fill
            alt="mern image"
          />
          <div className="absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] text-white z-10 p-2">
            <h2 className="py-2">Python Webpage Generator</h2>
          </div>
        </div>

        <div className="grid md:grid-cols-5 gap-8 py-8 max-w-[1240px] mx-auto p-2">
          <div className="col-span-4">
            <h2 className="mb-5">Description</h2>
            <p>
              This project is a Python script that generates a static HTML and
              CSS website template. The HTML and CSS are generated using Python
              f-strings. To generate the HTML and CSS files, the Python script
              includes two functions, create_html and create_css, that return
              the HTML and CSS strings, respectively. These strings are then
              written to files named index.html and style.css using Python's
              built-in file I/O functions. This project is useful for developers
              who want to quickly generate a HTML/CSS template for a website
              without having to write the HTML and CSS code from scratch. The
              template can be customized by modifying the strings returned by
              the create_html and create_css functions.
            </p>
            <a
              href="https://github.com/devjojr/python-webpage-generator"
              target="_blank"
              rel="noreferrer"
            >
              <button className="mt-4 mr-8 px-8 py-2">Code</button>
            </a>
          </div>

          <div className="py-4 rounded-xl col-span-4 md:col-span-1 shadow-xl shadow-gray-400">
            <div className="p-2">
              <p className="pb-2 text-center font-bold">Skills Demonstrated</p>
              <div className="grid grid-cols-3 md:grid-cols-1">
                <p className="flex items-center py-2">
                  <RiRadioButtonFill className="pr-1" /> Python
                </p>
                <p className="flex items-center py-2">
                  <RiRadioButtonFill className="pr-1" /> HTML
                </p>
                <p className="flex items-center py-2 text-[#141b24]">
                  <RiRadioButtonFill className="pr-1" /> CSS
                </p>
              </div>
            </div>
          </div>
          <Link href="/#projects">
            <p className="cursor-pointer underline">Go Back</p>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Merntodo;
